# This file is auto-generated, do not edit it

set(GENERATED_SOURCES
	${MOD_NAME}/Objects/AIZ/AIZTornado.c
	${MOD_NAME}/Objects/AIZ/Bloominator.c
	${MOD_NAME}/Objects/AIZ/Rhinobot.c
	${MOD_NAME}/Objects/AIZ/Sweep.c
	${MOD_NAME}/Objects/Common/Button.c
	${MOD_NAME}/Objects/Common/Decoration.c
	${MOD_NAME}/Objects/Common/ParallaxSprite.c
	${MOD_NAME}/Objects/Common/Platform.c
	${MOD_NAME}/Objects/Common/Water.c
	${MOD_NAME}/Objects/CPZ/Ball.c
	${MOD_NAME}/Objects/CPZ/Bubbler.c
	${MOD_NAME}/Objects/CPZ/CaterkillerJr.c
	${MOD_NAME}/Objects/CPZ/OneWayDoor.c
	${MOD_NAME}/Objects/CPZ/SpeedBooster.c
	${MOD_NAME}/Objects/CPZ/TubeSpring.c
	${MOD_NAME}/Objects/Cutscene/CutsceneHBH.c
	${MOD_NAME}/Objects/Cutscene/RubyPortal.c
	${MOD_NAME}/Objects/FBZ/Blaster.c
	${MOD_NAME}/Objects/FBZ/ElectroMagnet.c
	${MOD_NAME}/Objects/FBZ/FlameSpring.c
	${MOD_NAME}/Objects/FBZ/HangGlider.c
	${MOD_NAME}/Objects/FBZ/HangPoint.c
	${MOD_NAME}/Objects/FBZ/MagSpikeBall.c
	${MOD_NAME}/Objects/FBZ/Technosqueek.c
	${MOD_NAME}/Objects/FBZ/Tuesday.c
	${MOD_NAME}/Objects/FBZ/TwistingDoor.c
	${MOD_NAME}/Objects/GHZ/Batbrain.c
	${MOD_NAME}/Objects/GHZ/Bridge.c
	${MOD_NAME}/Objects/GHZ/BuzzBomber.c
	${MOD_NAME}/Objects/GHZ/CheckerBall.c
	${MOD_NAME}/Objects/GHZ/Chopper.c
	${MOD_NAME}/Objects/GHZ/Crabmeat.c
	${MOD_NAME}/Objects/GHZ/Fireball.c
	${MOD_NAME}/Objects/GHZ/Motobug.c
	${MOD_NAME}/Objects/GHZ/Newtron.c
	${MOD_NAME}/Objects/GHZ/SpikeLog.c
	${MOD_NAME}/Objects/GHZ/Splats.c
	${MOD_NAME}/Objects/GHZ/ZipLine.c
	${MOD_NAME}/Objects/Global/Spikes.c
	${MOD_NAME}/Objects/HCZ/Blastoid.c
	${MOD_NAME}/Objects/HCZ/ButtonDoor.c
	${MOD_NAME}/Objects/HCZ/Current.c
	${MOD_NAME}/Objects/HCZ/DCEvent.c
	${MOD_NAME}/Objects/HCZ/DiveEggman.c
	${MOD_NAME}/Objects/HCZ/Fan.c
	${MOD_NAME}/Objects/HCZ/Jawz.c
	${MOD_NAME}/Objects/HCZ/Jellygnite.c
	${MOD_NAME}/Objects/HCZ/MegaChopper.c
	${MOD_NAME}/Objects/HCZ/Pointdexter.c
	${MOD_NAME}/Objects/HCZ/ScrewMobile.c
	${MOD_NAME}/Objects/HCZ/TurboSpiker.c
	${MOD_NAME}/Objects/LRZ/Drillerdroid.c
	${MOD_NAME}/Objects/LRZ/DrillerdroidO.c
	${MOD_NAME}/Objects/LRZ/Fireworm.c
	${MOD_NAME}/Objects/LRZ/Flamethrower.c
	${MOD_NAME}/Objects/LRZ/Iwamodoki.c
	${MOD_NAME}/Objects/LRZ/LavaFall.c
	${MOD_NAME}/Objects/LRZ/LavaGeyser.c
	${MOD_NAME}/Objects/LRZ/LRZFireball.c
	${MOD_NAME}/Objects/LRZ/LRZRockPile.c
	${MOD_NAME}/Objects/LRZ/OrbitSpike.c
	${MOD_NAME}/Objects/LRZ/Rexon.c
	${MOD_NAME}/Objects/LRZ/RockDrill.c
	${MOD_NAME}/Objects/LRZ/Stalactite.c
	${MOD_NAME}/Objects/LRZ/Toxomister.c
	${MOD_NAME}/Objects/LRZ/Turbine.c
	${MOD_NAME}/Objects/LRZ/WalkerLegs.c
	${MOD_NAME}/Objects/MMZ/ConveyorBelt.c
	${MOD_NAME}/Objects/MMZ/ConveyorWheel.c
	${MOD_NAME}/Objects/MMZ/MatryoshkaBom.c
	${MOD_NAME}/Objects/MMZ/MechaBu.c
	${MOD_NAME}/Objects/MMZ/PohBee.c
	${MOD_NAME}/Objects/MMZ/Scarab.c
	${MOD_NAME}/Objects/MSZ/Armadiloid.c
	${MOD_NAME}/Objects/MSZ/Bumpalo.c
	${MOD_NAME}/Objects/MSZ/Cactula.c
	${MOD_NAME}/Objects/MSZ/RollerMKII.c
	${MOD_NAME}/Objects/MSZ/RotatingSpikes.c
	${MOD_NAME}/Objects/MSZ/SwingRope.c
	${MOD_NAME}/Objects/MSZ/Tornado.c
	${MOD_NAME}/Objects/OOZ/Aquis.c
	${MOD_NAME}/Objects/OOZ/Octus.c
	${MOD_NAME}/Objects/OOZ/PullSwitch.c
	${MOD_NAME}/Objects/OOZ/PushSpring.c
	${MOD_NAME}/Objects/OOZ/Sol.c
	${MOD_NAME}/Objects/OOZ/Valve.c
	${MOD_NAME}/Objects/PGZ/Acetone.c
	${MOD_NAME}/Objects/PGZ/Crate.c
	${MOD_NAME}/Objects/PGZ/DoorTrigger.c
	${MOD_NAME}/Objects/PGZ/Dragonfly.c
	${MOD_NAME}/Objects/PGZ/FrostThrower.c
	${MOD_NAME}/Objects/PGZ/Ice.c
	${MOD_NAME}/Objects/PGZ/IceBomba.c
	${MOD_NAME}/Objects/PGZ/Ink.c
	${MOD_NAME}/Objects/PGZ/InkWipe.c
	${MOD_NAME}/Objects/PGZ/JuggleSaw.c
	${MOD_NAME}/Objects/PGZ/PetalPile.c
	${MOD_NAME}/Objects/PGZ/Press.c
	${MOD_NAME}/Objects/PGZ/PrintBlock.c
	${MOD_NAME}/Objects/PGZ/PSZDoor.c
	${MOD_NAME}/Objects/PGZ/SP500.c
	${MOD_NAME}/Objects/PGZ/Woodrow.c
	${MOD_NAME}/Objects/SBZ/Bomb.c
	${MOD_NAME}/Objects/SBZ/Caterkiller.c
	${MOD_NAME}/Objects/SBZ/Orbinaut.c
	${MOD_NAME}/Objects/SPZ/Canista.c
	${MOD_NAME}/Objects/SPZ/CircleBumper.c
	${MOD_NAME}/Objects/SPZ/Clapperboard.c
	${MOD_NAME}/Objects/SPZ/DirectorChair.c
	${MOD_NAME}/Objects/SPZ/FilmReel.c
	${MOD_NAME}/Objects/SPZ/LEDPanel.c
	${MOD_NAME}/Objects/SPZ/MicDrop.c
	${MOD_NAME}/Objects/SPZ/PathInverter.c
	${MOD_NAME}/Objects/SPZ/RockemSockem.c
	${MOD_NAME}/Objects/SPZ/Shutterbug.c
	${MOD_NAME}/Objects/SPZ/Tubinaut.c
	${MOD_NAME}/Objects/SSZ/Dango.c
	${MOD_NAME}/Objects/SSZ/FlowerPod.c
	${MOD_NAME}/Objects/SSZ/Hotaru.c
	${MOD_NAME}/Objects/SSZ/HotaruMKII.c
	${MOD_NAME}/Objects/SSZ/JunctionWheel.c
	${MOD_NAME}/Objects/SSZ/Kabasira.c
	${MOD_NAME}/Objects/SSZ/Kanabun.c
	${MOD_NAME}/Objects/SSZ/MSHologram.c
	${MOD_NAME}/Objects/SSZ/MSOrb.c
	${MOD_NAME}/Objects/SSZ/RTeleporter.c
	${MOD_NAME}/Objects/SSZ/SparkRail.c
	${MOD_NAME}/Objects/SSZ/SSZSpikeBall.c
	${MOD_NAME}/Objects/SSZ/YoyoPulley.c
	${MOD_NAME}/Objects/TMZ/BallHog.c
	${MOD_NAME}/Objects/TMZ/FlasherMKII.c
	${MOD_NAME}/Objects/TMZ/GymBar.c
	${MOD_NAME}/Objects/TMZ/LaunchSpring.c
	${MOD_NAME}/Objects/TMZ/MagnetSphere.c
	${MOD_NAME}/Objects/TMZ/SentryBug.c
	${MOD_NAME}/Objects/TMZ/TeeterTotter.c
	${MOD_NAME}/Objects/TMZ/WallBumper.c
)
